### ISSUE TITLE
Add ability to have full combined certs file under /etc/ssl/certs

### ISSUE THREAD

**Issue by puneetse** [clearlinux/clrtrust#19] opened 2018-10-15 17:40 UTC
`clrtrust` places the combined certs under `/var/cache/ca-certs/compat` . 

Some scripts and programs are created to expect the ca-certificates in a specific location - [steamCMD ](https://developer.valvesoftware.com/wiki/SteamCMD) for example looks at the Ubuntu/Debian location `/etc/ssl/certs/ca-certificates.crt` (FreeBSD and other distro users encounter a similar issue here)

A temporarily work around is by doing a `ln -s /var/cache/ca-certs/compat/ca-roots.pem /etc/ssl/certs/ca-certificates.crt` However when `clrtrust generate` runs again it will be overwritten.

Ideally programs have a more robust method for searching the system locations for trusted certificates, but perhaps this functionality to generate a .crt in alternate locations can be added or a change to the way symlinking is done to allow customization like this with `clrtrust`.

**Comment by busykai** [comment] 2018-10-17 03:41
`clrtrust` manages all the certificate in a single location (by design and due to stateless requirements in Clear Linux): `/var/cache/ca-certs`. All Clear Linux-provided packages are configured to use it.

"Well-known" locations provided for compatibility, such as mentioned above, are out of scope of what `clrtrust` is designed to do. It is expected that other components of the OS will take care of exposing it. In this case, I'd suggest that you file an issue in [clearlinux/distribution](https://github.com/clearlinux/distribution/issues).

**Closed as completed by busykai** 2018-10-17 03:41 UTC
